services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Controllers
    Passioneight\Bundle\PimcoreSteamWebApiBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Services
    Passioneight\Bundle\PimcoreSteamWebApiBundle\Service\:
        resource: '../../Service'

    # Commands
    Passioneight\Bundle\PimcoreSteamWebApiBundle\Command\:
        resource: '../../Command'
        tags: [ 'console.command' ]