services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Controllers
    Passioneight\PimcoreSteamWebApi\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Services
    Passioneight\PimcoreSteamWebApi\Service\:
        resource: '../../Service'
