services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#    Passioneight\Bundle\BundleTemplateBundle\Controller\:
#        resource: '../../Controller'
#        tags: ['controller.service_arguments']