services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Controllers
    Passioneight\Bundle\PimcoreSteamWebApiBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']